### ISSUE TITLE
Evaluate Bud code millenials

### ISSUE THREAD

**Issue by dittops** [the-crypt-keeper/can-ai-code#138]
https://huggingface.co/budecosystem/code-millenials-13b
https://huggingface.co/budecosystem/code-millenials-34b

**Comment by the-crypt-keeper** [comment]
@dittops competed. the 34b model is fairly solid while the 13b model shows some signs of overfitting; it could no longer tell me batman's real name

**Comment by dittops** [comment]
Thanks for evaluating and sharing the feedback.
