### ISSUE TITLE
Kindly evaluate ajibawa-2023/Code-290k-6.7B-Instruct

### ISSUE THREAD

**Issue by ajinkya123-robo** [the-crypt-keeper/can-ai-code#166]
Hello @the-crypt-keeper ,
 Trust you are doing good. Can you evaluate https://huggingface.co/ajibawa-2023/Code-290k-6.7B-Instruct as time permits. As discussed I have used DeepSeek-Coder-6.7B-Instruct as a base.
 It is trained on around 290000 set of codes. Along with Python, Java, JavaScript, GO, C++, Rust, Ruby, Sql, MySql, R, Julia, Haskell, etc. code with detailed explanation is used for training purpose. This model utilises Alpaca format.
 Thanks

**Comment by the-crypt-keeper** [comment]
@ajinkya123-robo Doing well thank you!  This one nails junior-v2 as usual but I'm also happy to report some progress on senior: with the `Vicuna-1p3-v2b` template this model achieved 56%.  Results did seem to be heavily prompt dependent here, falling back to the usual ~25% with the other formats.

**Comment by ajinkya123-robo** [comment]
Hello @the-crypt-keeper , I used the repo made available by DeepSeek-AI. Not sure if it has flaws but model seems to perform on same level as parent model. Very happy with the Senior result. Thank you very much for your time & effort.
