### ISSUE TITLE
Kindly Evaluate ajibawa-2023/Code-Mistral-7B

### ISSUE THREAD

**Issue by ajinkya123-robo** [the-crypt-keeper/can-ai-code#178]
Hello @the-crypt-keeper ,
   I hope you are doing great. Kindly evaluate this model as time permits.
Following are the general details:
This Model is trained on refined version of my dataset Code-290k-ShareGPT. Besides this it is trained on following datasets:
Code-Feedback
orca-math-word-problems-200k
Openhermes
The idea was to check how this Model will perform with both Code & Maths datasets. This model is very good with Coding. Maths is still hit & miss but you can test out this model.

This Model is trained on massive datasets so the results are very good. I have used ChatML prompt format.
Link: https://huggingface.co/ajibawa-2023/Code-Mistral-7B
Thank you very much for evaluating my earlier models.

**Comment by the-crypt-keeper** [comment]
Apologies for the delay, suffering a bad case of COVID. Planned for this week.

**Comment by ajinkya123-robo** [comment]
@the-crypt-keeper please please take care of yourself. I lost very dear person to covid. Take rest & recover completely. Side effects can linger for very long period so take necessary precautions. Wishing you speedy recovery  👍

**Comment by the-crypt-keeper** [comment]
@ajinkya123-robo Appreciate your concern, feeling much better now!  I've completed the eval of this model today and it has unusually strong JavaScript performance in particular.

**Comment by ajinkya123-robo** [comment]
Thank you very much @the-crypt-keeper . Good to know that you are feeling better. Can you evaluate Jamba. I have finetuned it on my dataset. Let me know if you can do it.
Once again thank you very much!!😊
