### ISSUE TITLE
Guide on how to evaluate models

### ISSUE THREAD

**Issue by kisimoff** [the-crypt-keeper/can-ai-code#180]
Im willing to test a few models and share the results. 
I've looked at the readme, but couldn't wrap my head around how to benchmark a model. Any help would be appriciated!

**Comment by the-crypt-keeper** [comment]
The docs definitely need a rewrite my apologies here.

The general flow is:

1) prepare.py
2) interview*.py
3) eval.py

In the dark days we had to deal with dozens of prompt formats, but these days prepare.py can be run with --chat hfmodel and it will sort it out.

Note that there are two interviews junior-v2 and senior, I usually only run senior on strong models that get >90% on junior.

**Comment by the-crypt-keeper** [comment]
Still working on the Code completion and FIM portions, but with the recent refactor all the requirements are working again, the interview process is greatly simplified and there is a [basic guide](https://github.com/the-crypt-keeper/can-ai-code/blob/main/GUIDE.md)
