### ISSUE TITLE
Links for AI coders

### ISSUE THREAD

**Issue by vasnt** [the-crypt-keeper/can-ai-code#19]
Would be helpful if (clickable) links for each of these tool is populated in this table. 

https://huggingface.co/spaces/mike-ravkine/can-ai-code-results

**Comment by the-crypt-keeper** [comment]
I agree whole heartedly and even have the url data ready, but I got stuck:
seems streamlit doesn't support clickable links in tables unless they are
bare URLs.

My workaround plan is adding additional column that would be a clickable
link to a "Model detail" page that shows the model in all its sizes and
quants.

**Comment by vasnt** [comment]
Thanks for prompt support. overviewed, most worked. below highlighted seems broken/404.

<img width="431" alt="image" src="https://github.com/the-crypt-keeper/can-ai-code/assets/117589240/22ace27e-292e-4994-a084-0b8655703704">

**Comment by the-crypt-keeper** [comment]
@vasnt good catch! fixed that one, let me know if you find any others.
