### ISSUE TITLE
Evaluate WizardLM-2 8x22B

### ISSUE THREAD

**Issue by krzysiekpodk** [the-crypt-keeper/can-ai-code#191]
hey,

Not sure if you have seen: https://prollm.toqan.ai/leaderboard

In my opinion the most interesting takeaway is if you filter by advanced in code-recent category (unseen in training) the only model that rival propetiary models with that selection is wizardlm-2 8x22b

It would be really interesting to see if your benchmark will also score it so high

**Comment by the-crypt-keeper** [comment]
@krzysiekpodk Evaluating a 160B model at FP16 is beyond my available resources as a hobbyist 😢 but I can blow some of this month's cloud GPU budget on trying the 4-bit quants - any preferences?

**Comment by the-crypt-keeper** [comment]
@krzysiekpodk Results are somewhat mixed:

![image](https://github.com/the-crypt-keeper/can-ai-code/assets/84680712/0dfdd8c5-e49a-4656-83f9-450949b64b5a)

Original Mixtral-Instruct-8x22B performs quite well no matter the quant: AWQ GPTQ and EXL2 are all within spitting distance of each other.

WizardLM2 8x22B AWQ appears to be broken and scores poorly. I could not find a GPTQ. EXL2 performs well.

**Comment by krzysiekpodk** [comment]
thank you!! This is interesting as it looks like good scores are still not consistent across different benchmarks for oss models, maybe its time for leaderboard of leaderborads? :D
