### ISSUE TITLE
Kindly evaluate ajibawa-2023/Code-Llama-3-8B

### ISSUE THREAD

**Issue by ajinkya123-robo** [the-crypt-keeper/can-ai-code#192]
Hello @the-crypt-keeper , 
   I hope you are now fully recovered & must be doing good. Can you kindly evaluate my model: https://huggingface.co/ajibawa-2023/Code-Llama-3-8B
   Looking forward to hearing from you.
   Thanks

**Comment by the-crypt-keeper** [comment]
@ajinkya123-robo Thanks I'm feeling much better. Evaluation was performed tonight, junior is fine as usual senior showed reasonably good JS performance but Python struggled a bit (looks like it produced input validation that was too tight)

**Comment by ajinkya123-robo** [comment]
Thank you very much @the-crypt-keeper for evaluating this model. Thanks for your time & effort. I truly appreciate it.
