### ISSUE TITLE
Does "openai-chatgpt" on huggingface leader board means ChatGPT3.5?

### ISSUE THREAD

**Issue by nai-kon** [the-crypt-keeper/can-ai-code#20]
Does "openai-chatgpt" on huggingface leader board means ChatGPT3.5 or 4?
![image](https://github.com/the-crypt-keeper/can-ai-code/assets/25865392/da220a89-bb60-4e76-9426-ba7fd5f9f416)

Thank you for this great project.

**Comment by the-crypt-keeper** [comment]
Yes, the benchmark leader is the original gpt-3.5-turbo model.

**Comment by nai-kon** [comment]
Ok, Thank you!

**Comment by blksith0** [comment]
Where is GPT-4 on the list?
