### ISSUE TITLE
Evaluate StableCoder

### ISSUE THREAD

**Issue by mroark1m** [the-crypt-keeper/can-ai-code#61]
https://huggingface.co/stabilityai/stablecode-completion-alpha-3b-4k
https://huggingface.co/stabilityai/stablecode-instruct-alpha-3b
https://huggingface.co/stabilityai/stablecode-completion-alpha-3b

❤️ the can-ai-code project!

**Comment by the-crypt-keeper** [comment]
Interested in these models so taking a look.

First issue I hit is the [generation_config.json](https://huggingface.co/stabilityai/stablecode-completion-alpha-3b-4k/blob/main/generation_config.json) in all 3 models seems to have a problem:

ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

It doesn't seem this model has any concept of pad_token_id so going to try to set it to 0 like all the other tokens.

**Comment by the-crypt-keeper** [comment]
Loading `stabilityai/stablecode-completion-alpha-3b` model in fp16 with accelerate (device_map='auto', torch_dtype='fp16') seems to produce absolute nonsense:

```
3/28 FactorialZeroShot python


def factorial(n):
        fact = 1;

 for i in range (2, int((math.sqrt)(float(((factor * fact) + ((4*i)*(5*(6+7))))/8)))-3 ):
         if (((int)((0+(9*(((-((-((((-(j)+k))^l))+m)^p)*o)/q))*r))/t)%u)==v and j<w:
                 return v

         elif k>z or l==y :
                 break


 else
 print "The number is not valid"
```

This model seems to have no concept of EOS or BOS so I dont think there's any way it will never stop generating.  This wouldn't be so bad if what it generated was in some kind of consitent format but its just absolute trash..

Think accelerate may be causing this so I tried to fall back to their recommended way to load the model looks like it's trying to do fp32 even though the actual model itself is fp16 but it OOMed a 24GB host during loading.  I am not clear how does a 6GB model need over 24GB to load, but I'll need a bigger host to revisit the completion model.

The `stabilityai/stablecode-instruct-alpha-3b` flavor works totally fine:

```
13/28 GCDMisnamed python

def gcd(a, b):
    if a == 0:
        return b

    return gcd(b % a, a)


# Driver code
print("GCD of", 8, "and", 12,"is")
print(gcd(8, 12))
```

This one performs as expected for a model of this size, I am giving it a sweep over some prompt formats and I'll update results with the best ones.

**Comment by the-crypt-keeper** [comment]
Instruct results are up.  I'll leave this issue open until I can loop back around to trying the code-complete with their exact recommened settings to see if that makes it behave.

**Comment by cannstandard** [comment]
Final version of stable-code-completion is now out: https://huggingface.co/stabilityai/stable-code-3b

Performed eval for code completion and fim tasks it gets 70-80% on junior-v2 about what you'd expect from an OK-ish 3b.
