### ISSUE TITLE
Create a requirements.txt and document pip dependencies of each interviewer 

### ISSUE THREAD

**Issue by the-crypt-keeper** [the-crypt-keeper/can-ai-code#71]
While reviewing #70, which adds a dependency on litellm, I realized that this repo hasn't actually got an explicit list of it's dependencies.

It probably makes sense to include both a generic `requirements.txt` with global dependencies (yaml, jinja, etc..) as well as add a column to the list of available interviewers in README.md with notes on which packages each interviewer requires.

**Comment by krrishdholakia** [comment]
hey @the-crypt-keeper what would an explicit list of dependencies here look like - i would assume this was covered by our pyproject.toml - https://github.com/BerriAI/litellm/blob/d0ec8446295d86f72c17e1c9c1b430f866ae1cc9/pyproject.toml#L9

**Comment by the-crypt-keeper** [comment]
as part of #180 there's now requirements.txt for the base scripts as well as transformers, vllm and litellm
