### ISSUE TITLE
Evaluate LosslessMegaCoder

### ISSUE THREAD

**Issue by Andreghetto** [the-crypt-keeper/can-ai-code#73]

**Comment by the-crypt-keeper** [comment]
@Andreghetto could you provide GitHub or HuggingFace links?

**Comment by Andreghetto** [comment]
Sure!
7b: https://huggingface.co/rombodawg/LosslessMegaCoder-llama2-7b-mini
13b: https://huggingface.co/rombodawg/LosslessMegaCoder-llama2-13b-mini

**Comment by the-crypt-keeper** [comment]
@Andreghetto Evaluation completed, this is a great model the 13B especially is the first model of it's size to score a perfect 100% on the python evaluation.
