### ISSUE TITLE
Evaluate codellama-instruct family

### ISSUE THREAD

**Issue by the-crypt-keeper** [the-crypt-keeper/can-ai-code#76]
https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-fp16

https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-fp16

Need to reverse-engineer prompt format from https://github.com/facebookresearch/codellama/blob/main/example_instructions.py

**Comment by the-crypt-keeper** [comment]
Its the same instruction format as llama2-chat, which makes this one straightforward hopefully.

**Comment by the-crypt-keeper** [comment]
Experimenting with some prompt formats.

No-system prompts work the best so far and sometimes result in this interesting response template:

```
 [INST] Write a python function factorial(n) with input n that returns the factorial of n using recursion. [/INST]  [PYTHON]
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
[/PYTHON]
[TESTS]
# Test case 1:
assert factorial(0) == 1
# Test case 2:
assert factorial(1) == 1
# Test case 3:
assert factorial(5) == 120
[/TESTS]
```

Extractor will have to be updated to understand this.  Haven't seen a JS version yet.

**Comment by the-crypt-keeper** [comment]
Caught a bug in the transformers interview for templates that start with `<s>` since this token is not decoded the interviewer failed to remove from the prompt from the answer which breaks downstream extraction.

Will need to re-evaluate Llama2-Chat with this fix

**Comment by the-crypt-keeper** [comment]
Narrowed it down to the two best prompt variants and the recommended sampling params from upstream.

7B looks quite good, but 13B scores lower on both languages.  This evaluation has been anything but smooth tripped several bugs so in case there are still more bugs I'm reserving judgement.

**Comment by the-crypt-keeper** [comment]
7B vs 13B compare posted, remaining bugs fixed but in general 13B is indeed worse on some of the tests

34B will be done as part of #80 once it's available.

**Comment by shrikrishnaholla** [comment]
> in general 13B is indeed worse on some of the tests

That is indeed surprising.
