### ISSUE TITLE
Evaluate codellama family & finetunes 34B at original FP16

### ISSUE THREAD

**Issue by the-crypt-keeper** [the-crypt-keeper/can-ai-code#80]
Follow up on #76, #77, #78, #81 and #82 with the FP16 variants:

https://huggingface.co/TheBloke/CodeLlama-34B-fp16

https://huggingface.co/TheBloke/CodeLlama-34B-Python-fp16

https://huggingface.co/TheBloke/CodeLlama-34B-Instruct-fp16

https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0

https://huggingface.co/Phind/Phind-CodeLlama-34B-v1

This evaluation requires A100 80GB or 2x 40GB

**Comment by krzysiekpodk** [comment]
Hi, I'm surprised by Phind v2 results - honestly, I was able to replace it with GPT3.5 for most of the common daily questions - I quickly scanned the results for Q5 and it seems it produced two solutions for most of the questions, I wonder if it could impact the result - I suggest re-using the prompt that emphasis giving only the code. additionally, Phind v1 is much worse in my testing vs. Phind v2 (which is also with alpaca format instead).

**Comment by the-crypt-keeper** [comment]
@krzysiekpodk Can you suggest a prompt format?  Multi-part answers are definitely a problem for the evaluator, it extracts only the first provided code-block (I tried to be 'smart' about this but anything else is just madness).
