### ISSUE TITLE
Evaluate Speechless-Llama2-Hermes-Orca-Platypus-WizardLM-13B

### ISSUE THREAD

**Issue by thorhojhus** [the-crypt-keeper/can-ai-code#98]
From preliminary testing it seems like a very promising merge:
https://huggingface.co/TheBloke/Speechless-Llama2-Hermes-Orca-Platypus-WizardLM-13B-GGUF

**Comment by the-crypt-keeper** [comment]
@thorhojhus I have evaluated the [original FP16](https://huggingface.co/uukuguy/speechless-llama2-hermes-orca-platypus-wizardlm-13b) it's up on the leaderboard in the llama2 group.  Its "ok" at code, very similar results to all the other super-duper-mega-merges I've tested, generally a bit worse then CodeLlama-13B if you are looking for code specifically.
